### ISSUE TITLE
when someone readys up the blacklist goes away

### ISSUE THREAD

**Issue by thevipe** [tristanmcpherson/RoR2ItemManager#2]
m not sure if you or @wildbook is in control of UnhideGameRules but there's no GitHub to put issues up for it this seemed like a good place because it has to do with item management 

the blacklisting seems to work but the  UI doesn't tell you its blacklisted either but if someone presses ready it screws you over and you have to reset the whole lobby if you are trying to blacklist items

**Comment by wildbook** [comment]
Now this is a really late reply as I missed the ping, sorry about that.
I haven't touched UnhideGameRules, and as far as I remember @RyanPallesen was the author of it.
